name:                haskell-scratch-pad
version:             0.1.0.0
github:              "wraithjpr/haskell-scratch-pad"
license:             BSD3
author:              "James Wraith"
maintainer:          "james.p.r.wraith"
copyright:           "James Wraith 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            personal

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wraithjpr/haskell-scratch-pad#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-scratch-pad-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-scratch-pad

tests:
  haskell-scratch-pad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-scratch-pad
